name: Build, Push, and Deploy to EKS

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/hello-world:latest
            ghcr.io/${{ github.repository_owner }}/hello-world:${{ env.IMAGE_TAG }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::<account-id>:role/<GitHubActionsRole>
          aws-region: us-east-1

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name play-karpenter

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Deploy to EKS using Helm
        run: |
          helm upgrade --install express-hello ./helm/express-hello \
            --namespace default \
            --create-namespace \
            --set image.repository=ghcr.io/${{ github.repository_owner }}/hello-world \
            --set image.tag=${{ env.IMAGE_TAG }}
